apiVersion: cdi.kubevirt.io/v1beta1
kind: DataSource
metadata:
  annotations:
    operator-sdk/primary-resource: openshift-cnv/ssp-kubevirt-hyperconverged
    operator-sdk/primary-resource-type: SSP.ssp.kubevirt.io
  name: OS # everywhere with OS as a value should be replaced with the target os name.
  namespace: openshift-virtualization-os-images
  labels:
    app.kubernetes.io/component: storage
    app.kubernetes.io/managed-by: cdi-controller
    app.kubernetes.io/part-of: hyperconverged-cluster
    app.kubernetes.io/version: 4.10.5
    cdi.kubevirt.io/dataImportCron: OS-image-cron
spec:
  source: {}
  # pvc, url, or other with target image would be added here.
